site_name: Projekt Notion
site_description: Instrukcja pracy zespołowej z Notion
site_author: Gabriela Łacna Alicja Niedzielska

theme:
  name: mkdocs
  locale: en
  highlightjs: true
  hljs_style: default
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: indigo
    accent: pink
  logo: img/logo.png
  style: flatly

nav:
  - Strona główna: index.md
  - Autorzy: autorzy.md
  - O Notion: o-notion.md
  - Funkcje: funkcje.md
  - Konfiguracja: konfiguracja.md
  - Wdrożenie: wdrozenie.md
  - Przykłady: przyklady.md
  - Polityka bezpieczeństwa: polityka-bezpieczenstwa.md

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences